apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

replacements:
# External secrets IAM role
  - source:
      kind: ConfigMap
      name: example-configmap
      fieldPath: data.example_arn
      namespace: demo
    targets:
      - select:
          kind: ServiceAccount
          namespace: demo
        fieldPaths:
          - metadata.annotations.[eks.amazonaws.com/role-arn]